## 1.

In [1]:
import torch
import torch.nn as nn

In [2]:
data = torch.Tensor([1,2,3])
data

tensor([1., 2., 3.])

In [3]:
softmax_function = nn.Softmax(dim=0)
result = softmax_function(data)
print(result)

tensor([0.0900, 0.2447, 0.6652])


In [10]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total
    
my_softmax = MySoftmax()
result = my_softmax(data)
print(result)



tensor([0.0900, 0.2447, 0.6652])


In [11]:
data = torch.Tensor([1,2,300000000])
data

tensor([1.0000e+00, 2.0000e+00, 3.0000e+08])

In [12]:
my_softmax = MySoftmax()
result = my_softmax(data)
print(result)

tensor([0., 0., nan])


In [17]:
data = torch.Tensor([1,2,30000])

In [18]:
class StableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        c = torch.max(x, dim = 0)
        x_exp = torch.exp(x-c.values)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total
    
my_softmax = StableSoftmax()
result = my_softmax(data)
print(result)



tensor([0., 0., 1.])


## 2.

In [21]:
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        print(f'Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}')

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        print(f'Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}')

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        print(f'Doctor - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}')

In [24]:
student1 = Student( name ="studentA", yob =2010 , grade ="7")
student1 . describe ()

teacher1 = Teacher( name ="teacherA", yob =1969 , subject ="Math")
teacher1 . describe ()

doctor1 = Doctor( name ="doctorA", yob =1980 , specialist ="Surgery")
doctor1 . describe ()

Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1980 - Specialist: Surgery


In [40]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.person = []

    def add_person(self, person):
        self.person.append(person)

    def describe(self):
        print(f'Ward: {self.name}')
        for person in self.person:
            person.describe()

    def count_doctor(self):
        count = 0
        for person in self.person:
            if isinstance(person,Doctor):
                count += 1
        return count
    
    def sort_age(self):
        self.person.sort(key = lambda x: x.yob)

    def compute_average(self):
        list_teacher_yob = []
        for person in self.person:
            if isinstance(person, Teacher):
                list_teacher_yob.append(person.yob)
        return sum(list_teacher_yob) / len(list_teacher_yob)
    
teacher2 = Teacher ( name ="teacherB ", yob =1995 , subject =" History ")
doctor2 = Doctor ( name ="doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name ="Ward1")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . describe ()


print ("\nAfter sorting Age of Ward1 people ")
ward1 . sort_age ()
ward1 . describe ()

print(ward1.compute_average())

Ward: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB  - YoB: 1995 - Subject:  History 
Doctor - Name: doctorA - YoB: 1980 - Specialist: Surgery
Doctor - Name: doctorB  - YoB: 1975 - Specialist:  Cardiologists 

After sorting Age of Ward1 people 
Ward: Ward1
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorB  - YoB: 1975 - Specialist:  Cardiologists 
Doctor - Name: doctorA - YoB: 1980 - Specialist: Surgery
Teacher - Name: teacherB  - YoB: 1995 - Subject:  History 
Student - Name: studentA - YoB: 2010 - Grade: 7
1982.0


## 3.

In [43]:
class MyStack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []
    
    def is_empty(self):
        return len(self.items) == 0
    
    def is_full(self):
        return len(self.items) == self.capacity
    
    def pop(self):
        if self.is_empty():
            print('Underflow')
            return None
        else:
            return self.items.pop()
        
    def push(self, item):
        if self.is_full():
            print('Overflow')
        else:
            self.items.append(item)

    def top(self):
        if self.is_empty():
            print('Stack is empty')
            return None
        else:
            return self.items[-1]
        
stack1 = MyStack ( capacity =5)
stack1 . push (1)
stack1 . push (2)
print ( stack1 . is_full () )
print ( stack1 . is_full ())
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . is_empty () )


False
False
2
2
1
1
True


## 4.

In [47]:
class MyQueue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []
  
    def is_empty(self):
        return len(self.items) == 0
    
    def is_full(self):
        return len(self.items) == self.capacity
    
    def dequeue(self):
        if self.is_empty():
            print('Underflow')
            return None
        else:
            first = self.items[0]
            self.items.pop(0)
            return first
        
    def enqueue(self, item):
        if self.is_full():
            print('Overflow')
        else:
            self.items.append(item)

    def front(self):
        if self.is_empty():
            print('Stack is empty')
            return None
        else:
            return self.items[0]
    
queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
queue1 . enqueue (2)
print ( queue1 . is_full () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . is_empty () )

False
1
1
2
2
True


## IOU

In [1]:
def compute(boxA, boxB):
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)

    boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
    boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)

    return interArea / float(boxAArea + boxBArea - interArea)

In [2]:
boxA = (0,0,5,5)
boxB = (2.5,2.5,7.5,7.5)
error = compute(boxA, boxB)

In [3]:
print(error)

0.20502092050209206


## Non Maximum Suppression

In [5]:
def non_max_suppression(boxes, scores, threshold):
    sorted_indices = sorted(range(len(scores)), key=lambda k: scores[k], reverse=True)
    kept_indices = []

    while sorted_indices:
        i = sorted_indices.pop(0)
        kept_indices.append(i)

        filtered_indices = []
        for j in sorted_indices:
            iou = compute(boxes[i], boxes[j])
            if iou <= threshold:
                filtered_indices.append(j)
                
            sorted_indices = filtered_indices

    return kept_indices

In [6]:
import numpy as np

boxes = [
    [12,84,140,212],
    [24,84,152,212],
    [36,84,164,212],
    [12,96,140,224],
    [24,96,152,224],
    [24,108,152,236]
]
scores = [0.3, 0.4, 0.5, 0.6, 0.7]
iou_threshold = 0.3
kept_indices = non_max_suppression(boxes, scores, iou_threshold)

In [7]:
print("Kept boxes after Non-Maximum Suppression:")
for index in kept_indices: 
    print(f'Box: {boxes[index]}, Score: {scores[index]}') 

Kept boxes after Non-Maximum Suppression:
Box: [24, 96, 152, 224], Score: 0.7


In [1]:
#### K-D Tree
class Node:
    def __init__(self, point, left=None, right=None):
        self.point = point
        self.left = left
        self.right = right

    

In [2]:
def build_kd_tree(points, depth = 0):
    if not points:
        return None
    
    k = len(points[0])  # number of dimensions
    axis = depth % k
    print("axis:", axis)
     
    points.sort(key=lambda x: x[axis])
    median = len(points) // 2
    print("median:", median)

    return Node(
        point=points[median],
        left=build_kd_tree(points[:median], depth + 1),
        right=build_kd_tree(points[median + 1:], depth + 1)
    )


In [3]:
points = [(1,2), (2,6), (3,4), (5,6), (7,8), (8, 3 )
          ]
kd_tree = build_kd_tree(points)

axis: 0
median: 3
axis: 1
median: 1
axis: 0
median: 0
axis: 0
median: 0
axis: 1
median: 1
axis: 0
median: 0


In [10]:
import math
def distance_squared(point1, point2):
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(point1, point2)))

def closer_point(new_data, nearest_node, root_node):
    if nearest_node is None:
        return root_node
    if distance_squared(new_data, nearest_node) < distance_squared(new_data, root_node):
        return nearest_node
    else:
        return root_node
    
                 
def nearest_neighbor(node, point, depth=0, best=None):
    if node is None:
        return best

    k = len(point)
    axis = depth % k

    next_branch = None
    opposite_branch = None

    if point[axis] < node.point[axis]:
        next_branch = node.left
        opposite_branch = node.right
    else:
        next_branch = node.right
        opposite_branch = node.left

    best = closer_point(point, nearest_neighbor(next_branch, point, depth + 1, best), node.point)

    if (point[axis] - node.point[axis]) ** 2 < distance_squared(point, best):
        best = closer_point(point, nearest_neighbor(opposite_branch, point, depth + 1, best), best)


In [12]:
query_point = (6,5)
nearest_point = nearest_neighbor(kd_tree, query_point)