## 1.

In [1]:
import torch
import torch.nn as nn

In [2]:
data = torch.Tensor([1,2,3])
data

tensor([1., 2., 3.])

In [3]:
softmax_function = nn.Softmax(dim=0)
result = softmax_function(data)
print(result)

tensor([0.0900, 0.2447, 0.6652])


In [10]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total
    
my_softmax = MySoftmax()
result = my_softmax(data)
print(result)



tensor([0.0900, 0.2447, 0.6652])


In [11]:
data = torch.Tensor([1,2,300000000])
data

tensor([1.0000e+00, 2.0000e+00, 3.0000e+08])

In [12]:
my_softmax = MySoftmax()
result = my_softmax(data)
print(result)

tensor([0., 0., nan])


In [17]:
data = torch.Tensor([1,2,30000])

In [18]:
class StableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        c = torch.max(x, dim = 0)
        x_exp = torch.exp(x-c.values)
        total = x_exp.sum(0, keepdims=True)
        return x_exp / total
    
my_softmax = StableSoftmax()
result = my_softmax(data)
print(result)



tensor([0., 0., 1.])


## 2.

In [21]:
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        print(f'Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}')

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        print(f'Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}')

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        print(f'Doctor - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}')

In [24]:
student1 = Student( name ="studentA", yob =2010 , grade ="7")
student1 . describe ()

teacher1 = Teacher( name ="teacherA", yob =1969 , subject ="Math")
teacher1 . describe ()

doctor1 = Doctor( name ="doctorA", yob =1980 , specialist ="Surgery")
doctor1 . describe ()

Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1980 - Specialist: Surgery


In [40]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.person = []

    def add_person(self, person):
        self.person.append(person)

    def describe(self):
        print(f'Ward: {self.name}')
        for person in self.person:
            person.describe()

    def count_doctor(self):
        count = 0
        for person in self.person:
            if isinstance(person,Doctor):
                count += 1
        return count
    
    def sort_age(self):
        self.person.sort(key = lambda x: x.yob)

    def compute_average(self):
        list_teacher_yob = []
        for person in self.person:
            if isinstance(person, Teacher):
                list_teacher_yob.append(person.yob)
        return sum(list_teacher_yob) / len(list_teacher_yob)
    
teacher2 = Teacher ( name ="teacherB ", yob =1995 , subject =" History ")
doctor2 = Doctor ( name ="doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name ="Ward1")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . describe ()


print ("\nAfter sorting Age of Ward1 people ")
ward1 . sort_age ()
ward1 . describe ()

print(ward1.compute_average())

Ward: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB  - YoB: 1995 - Subject:  History 
Doctor - Name: doctorA - YoB: 1980 - Specialist: Surgery
Doctor - Name: doctorB  - YoB: 1975 - Specialist:  Cardiologists 

After sorting Age of Ward1 people 
Ward: Ward1
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorB  - YoB: 1975 - Specialist:  Cardiologists 
Doctor - Name: doctorA - YoB: 1980 - Specialist: Surgery
Teacher - Name: teacherB  - YoB: 1995 - Subject:  History 
Student - Name: studentA - YoB: 2010 - Grade: 7
1982.0


## 3.

In [43]:
class MyStack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []
    
    def is_empty(self):
        return len(self.items) == 0
    
    def is_full(self):
        return len(self.items) == self.capacity
    
    def pop(self):
        if self.is_empty():
            print('Underflow')
            return None
        else:
            return self.items.pop()
        
    def push(self, item):
        if self.is_full():
            print('Overflow')
        else:
            self.items.append(item)

    def top(self):
        if self.is_empty():
            print('Stack is empty')
            return None
        else:
            return self.items[-1]
        
stack1 = MyStack ( capacity =5)
stack1 . push (1)
stack1 . push (2)
print ( stack1 . is_full () )
print ( stack1 . is_full ())
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . is_empty () )


False
False
2
2
1
1
True


## 4.

In [47]:
class MyQueue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.items = []
  
    def is_empty(self):
        return len(self.items) == 0
    
    def is_full(self):
        return len(self.items) == self.capacity
    
    def dequeue(self):
        if self.is_empty():
            print('Underflow')
            return None
        else:
            first = self.items[0]
            self.items.pop(0)
            return first
        
    def enqueue(self, item):
        if self.is_full():
            print('Overflow')
        else:
            self.items.append(item)

    def front(self):
        if self.is_empty():
            print('Stack is empty')
            return None
        else:
            return self.items[0]
    
queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
queue1 . enqueue (2)
print ( queue1 . is_full () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . is_empty () )

False
1
1
2
2
True
